# Generated by Django 5.2.5 on 2025-11-15 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_note', models.TextField()),
                ('vitals', models.JSONField(blank=True, default=dict)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('immunizations', models.JSONField(blank=True, default=list)),
                ('past_conditions', models.JSONField(blank=True, default=list)),
                ('procedures', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'is_patient': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ehr_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_patient_record', 'Can create patient record'), ('can_view_patient_record', 'Can view patient record'), ('can_update_patient_record', 'Can update patient record'), ('can_delete_patient_record', 'Can delete patient record')],
            },
        ),
    ]