# Generated by Django 5.2.5 on 2025-11-12 12:39

import server.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[
                server.accounts.validators.NINValidator()]),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[
                server.accounts.validators.NINValidator()]),
        ),
    ]
